# Generated by Django 3.1.6 on 2021-04-17 23:31

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('groovesweeperapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='songmodel',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='songmodel',
            name='db_song_id',
            field=models.CharField(default=69, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='songmodel',
            name='explicit_words',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='songmodel',
            name='lyrics',
            field=models.TextField(),
        ),
    ]
