# Generated by Django 3.1.6 on 2021-04-17 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groovesweeperapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songmodel',
            name='explicit_words',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='songmodel',
            name='lyrics',
            field=models.TextField(),
        ),
    ]
