# Generated by Django 3.1.6 on 2021-04-18 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groovesweeperapp', '0002_auto_20210417_2331'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='songmodel',
            managers=[
            ],
        ),
    ]
