# Generated by Django 3.1.6 on 2021-04-17 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groovesweeperapp', '0002_auto_20210417_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='songmodel',
            name='db_song_id',
            field=models.CharField(default=69, max_length=20),
            preserve_default=False,
        ),
    ]
